### PR TITLE
Fix JS slices

### LINKED ISSUE #339: JS runtime slice code truncates values
This issue makes it so that functions that call `DiplomatBuf.slice()` do not properly pass values to WASM, so calling functions like `ICU4XLineSegmenter.segment_utf16()` from JS will not produce the correct output.

This line https://github.com/rust-diplomat/diplomat/blob/19b6e413c7510d0942fe7b80aade64d8a77216c2/tool/src/js/runtime.mjs#L87
constructs a `Uint8Array` from a potentially wider typed array like `Uint16Array`. However, this particular signature produces an array with the same number of elements as the source, so values that won't fit into 8 bits will be truncated. So an array like this:

```
Uint16Array(20) [
  3585, 3619, 3640, 3603,
  3634, 3629, 3618, 3656,
  3634, 3648, 3604, 3636,
  3609, 3621, 3633, 3604,
  3626, 3609, 3634, 3617
]
```

would become:

```
Uint8Array(20) [
   1, 35, 56, 19, 50, 45, 34,
  72, 50, 64, 20, 52, 25, 37,
  49, 20, 42, 25, 50, 33
]
```

Easiest fix seems to be changing this to `new Uint8Array(slice.buffer)`. I believe this will also set the two array buffers to be equal (so `oldArray.buffer === newArray.buffer`), so I'm not completely sure if this is OK. 

Note that this change will also affect functions that use the slice's size. For example, in this function

https://github.com/unicode-org/icu4x/blob/e41030cd05732ef7329388bffdd759cac96c2445/ffi/diplomat/js/include/ICU4XLineSegmenter.js#L140

the argument `buf_arg_input.size` might need to be changed to something like `buf_arg_input.size / 2` otherwise the segmented indices will go up to twice the actual length. I'm not sure which files to change for that one (maybe more of an ICU4X issue).

### PR DESCRIPTION
**Pull request by robertbastian**
This is currently broken for element sizes > 1, as byte size and slice size are not distinguished.

I'm also removing the constraint that slices can only be constructed from the correct `TypedArray`, as it's easy enough to construct them from arbitrary arrays.

Fixes #339

### CODE REVIEW

File: tool/src/js/runtime.mjs [hunk 1]
```diff
@@ -67,68 +67,73 @@ export function enumDiscriminant(wasm, ptr) {
...
-        // leak
-      } else {
-        console.error(`Failed to unregister DiplomatBuf at ${this.ptr}, this is a bug. Either it was never registered (leak), it was already unregistered (failed attempt to double free), or the unregister token was unrecognized (fallback to GC).`);
-      }
+  constructor(ptr, size, free) {
+    this.ptr = ptr;
+    this.size = size;
+    this.free = free;
+    this.leak = () => { };
+    this.garbageCollect = () => DiplomatBufferFinalizer(this, this.free);
```
Comment (sffc) [inline tool/src/js/runtime.mjs:135]: Issue: What does `DiplomatBufferFinalizer(this, this.free)` do? Are you intending to do `DiplomatBufferFinalizer.register(this, this.free, this)` ?

File: tool/src/js/runtime.mjs [hunk 2]
```diff
@@ -67,68 +67,73 @@ export function enumDiscriminant(wasm, ptr) {
...
-      if (successfully_unregistered) {
-        // leak
-      } else {
-        console.error(`Failed to unregister DiplomatBuf at ${this.ptr}, this is a bug. Either it was never registered (leak), it was already unregistered (failed attempt to double free), or the unregister token was unrecognized (fallback to GC).`);
-      }
+  constructor(ptr, size, free) {
+    this.ptr = ptr;
+    this.size = size;
+    this.free = free;
+    this.leak = () => { };
```
Comment (sffc) [inline tool/src/js/runtime.mjs:134]: Issue: `leak` doesn't do anything?

Did you make the finalization registry "opt-in" instead of "opt-out", like you need to explicitly call the `.garbageCollect()` function? Why?

**Review by sffc — CHANGES_REQUESTED** [review]

File: tool/src/js/runtime.mjs (hunk 1 above)
Comment (robertbastian) [reply tool/src/js/runtime.mjs:135]: The last param is only required for unregistering

File: tool/src/js/runtime.mjs (hunk 2 above)
Comment (robertbastian) [reply tool/src/js/runtime.mjs:134]: Because before it was not explicit at the call site, and the buffers would register and then unregister with the finalizer. Now every call site calls either free, leak, or garbage collect.

Comment (robertbastian) [reply tool/src/js/runtime.mjs:134]: And leak does nothing, that's the point but it makes it explicit at the call site.

**Review by Manishearth — APPROVED** [review]
great, thanks, this has been on my list to debug for a long time now

File: tool/src/js/runtime.mjs (hunk 2 above)
Comment (robertbastian) [reply tool/src/js/runtime.mjs:137]: done

File: tool/src/js/runtime.mjs (hunk 1 above)
Comment (robertbastian) [reply tool/src/js/runtime.mjs:138]: I don't think this is necessary to be in the code. Shane only brought this up because I removed the param, but I don't think it's common in JS to document omitted optionals, they are treated more like overloads.

**Review by Manishearth — APPROVED** [review]
