### PR TITLE
Nanobind ZST opaque templating

### LINKED ISSUE #1050: Nanobind crashes on calling Opaque ZST constructor twice
Failing test in
https://github.com/rust-diplomat/diplomat/pull/1049

### PR DESCRIPTION
**Pull request by tyler-zeromatter**
Closes #1050. 

Took a while to find a solution that seemingly works correctly, but I feel confident about this approach. A lot of TODOs with this one:

- [x] Document/explain choices
- [X] ~~optional support~~ (Optional pointers are still pointers on the HIR side)
- [x] Lambda support
- [x] ~~Fix stringifier bug~~ (#1054)
- [x] Add askama generation for:
  - [x] Add
  - [X] ~~Add assign~~ (cannot return a value)
  - [x] Sub
  - [X] ~~Sub assign~~
  - [x] Mul
  - [X] ~~Mul assign~~
  - [x] Div
  - [X] ~~Div assign~~
  - [x] Static Getter
  - [x] Getter
  - [x] Getter + setter
  - [x] Iterator
  - [x] Iterable
  - [x] Indexer
  - [x] Fallible indexer
  - [x] Unsupported special methods
  - [x] Stringifier (as error result)
  - [X] ~~Comparison~~
- [x] Add tests (call the method twice) for:
  - [x] `result<T, E>`
    - [x] Where T is an opaque ZST
    - [x] Where E is an opaque ZST
    - [x] Where both T and E are opaque ZSTs  
  - [x] `optional<T>` 
  - [x] Constructor
  - [x] Static methods
  - [x] Mutable member methods
  - [x] Const member methods
  - [x] Add
  - [X] ~~Add assign~~
  - [x] Sub
  - [X] ~~Sub assign~~
  - [x] Mul
  - [X] ~~Mul assign~~
  - [x] Div
  - [X] ~~Div assign~~
  - [x] Getter
  - [x] Static getter
  - [x] Getter + Setter together
  - [x] Iterator
  - [x] Iterable
  - [x] Indexer
  - [x] Fallible indexer
  - [x] Stringifier
- [x] Simplify templating (not blocking)
  - [x] Give the template functions better names
- [x] Check for memory leaks
- [x] Rebase and clean-up PR

### CODE REVIEW

**Comment by tyler-zeromatter** [comment]
Thankfully, this solution compiles on the Linux CI runner, and it looks like we have failing tests already.

**Comment by tyler-zeromatter** [comment]
@Manishearth mostly looking for your approval on [`maybe_alloc_zst`](https://github.com/rust-diplomat/diplomat/pull/1053/changes#diff-7a98aefab82eb1f225c3e5ceb86648a56667b3cfcb2af0dbf715db1340edc4abR319) to see if there are any potential issues there you can think of.

File: tool/templates/nanobind/function_base.cpp.jinja [hunk 1]
```diff
@@ -1,22 +1,60 @@
...
+    {%- let success_is_owned_op = op.is_owned() -%}
+    {%- else -%}
+    {%- let success_is_owned_op = false -%}
+    {%- endif -%}
+    {%- if success_is_owned_op -%}
+    {{-pre_call-}}{{- caller() -}}{{- post_call -}}
+    {%- else -%}
+    {%- decl failure_is_owned_op -%}
+    {%- if let hir::ReturnType::Fallible(_s, Some(hir::Type::Opaque(op))) = m.method.output -%}
+    {%- let failure_is_owned_op = true -%}
```
Comment (walter-zeromatter) [inline tool/templates/nanobind/function_base.cpp.jinja]: This should be able to be simplified to just be `let failure_is_owned_op = <if condition>`

File: tool/templates/nanobind/function_base.cpp.jinja [hunk 2]
```diff
@@ -1,22 +1,60 @@
...
+{%- if overload_params.len() > 0 -%}
+nb::overload_cast<{% for p in overload_params -%} {{- p.type_name -}} {%- if !loop.last -%}, {% endif %} {%- endfor
+    -%}>(
+{%- endif -%}
+&{{- method_name_cpp_inner() -}}
+{%- if m.overloads.len() > 0 -%} ) {%- endif -%}
+{%- endmacro -%}
+{%- macro method_name_cpp(pre_call="std::move(maybe_op_unwrap(", post_call="))") -%}
+    {%- decl success_is_owned_op -%}
+    {%- if let hir::SuccessType::OutType(hir::Type::Opaque(op)) = m.method.output.success_type() -%}
```
Comment (walter-zeromatter) [inline tool/templates/nanobind/function_base.cpp.jinja:12]: This kind of branch statement looks a little code-smelly to me, much like the one below, but given the complexity of the match statement that'd be required I'm not 100% sure how to simplify it off the top of my head

File: feature_tests/src/attrs.rs [hunk 3]
```diff
@@ -505,4 +497,136 @@ pub mod ffi {
     // C++ will not generate this, since it has all features disabled by default (see lib.rs)
     #[diplomat::attr(not(feature=some_feature), disable)]
     pub struct FeatureTest();
+
+    #[diplomat::attr(not(nanobind), disable)]
+    #[diplomat::opaque]
+    pub struct OpaqueZST;
```
Comment (Manishearth) [inline feature_tests/src/attrs.rs:507]: nit: document this with a link to the issue so it's clear why we have this

**Review by Manishearth — APPROVED** [review]
Not looking too closely at the nanobind code, seems fine.

**Review by Walter-Reactor — COMMENTED** [review]
My only complaint would be that the structuring of the adjacent if-else blocks in the askama templates is a little hard to parse, but that really is just a nit. You really should try and address your cleanup todo note before this actually merges though

File: tool/templates/nanobind/function_base.cpp.jinja (hunk 2 above)
Comment (tyler-zeromatter) [reply tool/templates/nanobind/function_base.cpp.jinja:12]: Askama is *pretty* good at being able to evaluate rust in the template syntax, but not amazing. There might be some tricks to reduce footprint here, I'll see what I can do.

File: tool/templates/nanobind/function_base.cpp.jinja (hunk 1 above)
Comment (tyler-zeromatter) [reply tool/templates/nanobind/function_base.cpp.jinja]: Ah, we can't, I forgot to add a check for `failure_is_owned_op = op.is_owned()`, so this might have to stay as is. Will try to simplify

File: tool/templates/nanobind/function_base.cpp.jinja (hunk 2 above)
Comment (tyler-zeromatter) [reply tool/templates/nanobind/function_base.cpp.jinja:12]: I was able to simplify the later if statements, but not the if-else chains here
