### PR TITLE
Various JS fixes

### LINKED ISSUE #190: Fix borrowing from non-opaque struct
I found an uncaught bug in #189 where if you take a borrowing non-opaque struct, and return a value that borrows from it, no edges are attached. The correct behavior would be to attach an edge to all fields of the struct that have any lifetime that the return type has.

### PR DESCRIPTION
**Pull request by QnnOkabayashi**
* Removed a test that broke #191.
* Opaque constructors are now responsible for storing lifetime edges and `FinalizationRegistry` registration for underlying data _if it's owned_.
* Fix #190 so now we can support arbitrarily nested input and output structs with borrows, and always attach lifetime edges to the exact fields of the output struct that depend on them.
* Support non-opaque structs borrowing `&str` and primitive slices (except `&[bool]` and `&[char]` for now).

Internally, this PR also brings a ton of code cleanup to the JS conversion codegen, particularly translating JS values into values that the WASM ABI supports.

### CODE REVIEW

File: feature_tests/src/lifetimes.rs [hunk 1]
```diff
@@ -16,11 +16,12 @@ pub mod ffi {
         }
     }
 
-    impl<'b, 'a: 'b> Bar<'b, 'a> {
-        pub fn foo(&'b self) -> &'b Foo<'a> {
-            self.0
-        }
-    }
+    // TODO: add after #191 is resolved.
```
Comment (Manishearth) [inline feature_tests/src/lifetimes.rs:19]: must we remove this test if it's still testing JS stuff (and not breaking C++)?

 we can leave a comment that it's untested in C++

File: tool/src/js/types.rs [hunk 2]
```diff
@@ -69,9 +69,9 @@ pub fn return_type_form(typ: &ast::TypeName, in_path: &ast::Path, env: &Env) ->
 
         ast::TypeName::Reference(_, _mut, _lt) => ReturnTypeForm::Scalar,
 
-        ast::TypeName::StrReference(..) => ReturnTypeForm::Scalar,
+        ast::TypeName::StrReference(..) => ReturnTypeForm::Complex,
```
Comment (Manishearth) [inline tool/src/js/types.rs:72]: good catch

**Review by Manishearth — APPROVED** [review]

File: feature_tests/src/lifetimes.rs (hunk 1 above)
Comment (QnnOkabayashi) [reply feature_tests/src/lifetimes.rs:19]: We get 
```
thread 'main' panicked at 'not yet implemented: Returning references from Rust to C++ is not currently supported', tool/src/cpp/conversions.rs:177:13
```
When running `./regen_integration_tests.sh` when we have this test in, is that okay?

Comment (Manishearth) [reply feature_tests/src/lifetimes.rs]: Wait, did you readd it? Please remove it, I made this comment here assuming that the regen had been succeeding with this code previously.

(Our regen tests really need to be better to catch this)

Comment (QnnOkabayashi) [reply feature_tests/src/lifetimes.rs]: https://github.com/rust-diplomat/diplomat/pull/195

My bad. In retrospect this probably should've been a separate PR anyways.
