### PR TITLE
Fix namespacing of result types in C

### LINKED ISSUE #155: Multiple results of the same type don't work in C
This is causing failures in https://github.com/unicode-org/icu4x/pull/1944

Basiclaly, when creating `Result` types for C, they get put in `result_foo_bar.h`, but each is namespaced according to its source (e.g. `bidi_ffi_result_foo_bar.h`. They get concatenated in the two files, with duplicated include guards, which effectively ends up causing the seocnd one to not be included.

<details>

```c

#ifndef result_void_void_H
#define result_void_void_H
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "diplomat_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef struct bidi_ffi_result_void_void {
    bool is_ok;
} bidi_ffi_result_void_void;
#ifdef __cplusplus
}
#endif
#endif
#ifndef result_void_void_H
#define result_void_void_H
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "diplomat_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef struct decimal_ffi_result_void_void {
    bool is_ok;
} decimal_ffi_result_void_void;
#ifdef __cplusplus
}
#endif
#endif
```

</details>

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #155

We don't actually need full namespacing here, just naming everything diplomat_result_foo_bar is fine

### CODE REVIEW

**Comment by Manishearth** [comment]
@QnnOkabayashi would you like to review this?

File: tool/src/c/results.rs [hunk 1]
```diff
@@ -42,28 +41,24 @@ pub fn collect_results<'a>(
...
 
-pub fn gen_result<W: fmt::Write>(
-    typ: &ast::TypeName,
-    in_path: &ast::Path,
-    env: &Env,
-    out: &mut W,
-) -> fmt::Result {
+pub fn gen_result<W: fmt::Write>(typ: &ast::TypeName, env: &Env, out: &mut W) -> fmt::Result {
     if let ast::TypeName::Result(ok, err) = typ {
-        let result_name = format!("{}_{}", in_path.elements.join("_"), name_for_type(typ));
```
Comment (QnnOkabayashi) [inline tool/src/c/results.rs:52]: So here we're removing the prefixes to make the paths simpler, right?

**Review by QnnOkabayashi — COMMENTED** [review]
I think I follow what the changes accomplish but I still don't understand how using less namespaces resolves naming conflicts

File: tool/src/c/results.rs (hunk 1 above)
Comment (Manishearth) [reply tool/src/c/results.rs:52]: Yes.

There's no actual namespacing needed for the result itself since two results with the same types are the same result
