### PR TITLE
Fix `Method::params_held_by_output` ignoring lifetime bounds

### LINKED ISSUE #163: `Method::params_held_by_output` doesn't catch all cases
Bug introduced in #159 

Currently, `Method::params_held_by_output` uses a naive strategy for finding params by traversing the type tree and seeing if any lifetimes share the same name as something in the output. This introduces a bug where if a method introduces lifetime `'b: 'a`, and a param uses `'b` and the output uses `'a` and borrows from the param by lifetime coercion, it won't be detected because it has a different name. As an example, consider the following:
```rust
#[diplomat::opaque]
pub struct Wrapper<'a>(&'a MyOpaqueType);

impl<'a> Wrapper<'a> {
    pub fn new<'b: 'a>(inner: &'b MyOpaqueType) -> Box<Wrapper<'a>> {
        Box::new(Self(inner))
    }
}
```
Here, the implementation thinks that `&'b MyOpaqueType` doesn't share any lifetimes with `Box<Wrapper<'a>>` because we don't consider the fact that `'b: 'a`, so the method would return an empty vec which is incorrect.

This could be really bad because in languages like JS, we depend on this information being correct for holding lifetime guards, so a faulty implementation could cause use-after-free bugs.

There are two approaches we can take:
1. Disallow bounds on lifetimes (easy)
2. Somehow build a lifetime resolution system by using the `LifetimeDef` types that we hold in the ast (hard)

### PR DESCRIPTION
**Pull request by QnnOkabayashi**
Fixes #163 

I implemented a basic lifetime dependency resolution algorithm that collects _all_ lifetimes in a `Method` that must live at least as long as the output type. It does this by doing DFS on the lifetime tree. My implementation is a little naive because it linearly scans through every unused lifetime relationship for each lifetime to determine how to traverse down the tree, but it should be fine because we're not expecting that many lifetimes or lifetime bounds.

The theoretically optimal solution would be to instead create a map from `'a` to a vec of `'b` for all `'b` such that `'b: 'a`, allowing us to traverse each edge of the tree in constant (or logn) time, but this introduces a lot of allocations when we're not expecting that many lifetimes bounds in the first place, so I'm not sure if this is worth it.

Since this was kinda cognitively complex, I added a lot of tests and comments walking through the code.

Thanks to @Manishearth for implementation help.

### CODE REVIEW

File: core/src/ast/methods.rs [hunk 1]
```diff
@@ -115,69 +114,100 @@ impl Method {
...
-                    if let Some((Lifetime::Named(ref name), _)) = self_param.reference {
-                        if lifetimes.contains(name) {
-                            return true;
-                        }
+                let mut lifetimes = Vec::with_capacity(stack.len());
+
+                let mut unused_rules: Vec<&LifetimeDef> =
+                    self.introduced_lifetimes.iter().collect();
+
+                while let Some(sublifetime) = stack.pop() {
```
Comment (Manishearth) [inline core/src/ast/methods.rs:148]: nit: this code looks right, but should have a comment explaining what it's doing (and why)

**Review by Manishearth — APPROVED** [review]
lgtm overall, mergeable with some docs

**Review by Manishearth — APPROVED** [review]
